
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Diagnostics;

namespace YouXiArticle.Models
{
    /// <summary>
    /// The class representing the dbo.Tag table.
    /// </summary>
    [Table(Name="dbo.Tag")]
    public partial class Tag
        : YouXiArticleEntity
    {
        
        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Tag"/> class.
        /// </summary>
        [DebuggerNonUserCodeAttribute()]
        public Tag()
        {
            OnCreated();
            _siteSiteInfo = default(EntityRef<SiteInfo>);
            _articleTagList = new EntitySet<ArticleTag>(
                new System.Action<ArticleTag>(this.Attach_ArticleTagList),
                new System.Action<ArticleTag>(this.Detach_ArticleTagList));
            _urlTagList = new EntitySet<UrlTag>(
                new System.Action<UrlTag>(this.Attach_UrlTagList),
                new System.Action<UrlTag>(this.Detach_UrlTagList));
        }
        #endregion
        
        #region Column Mapped Properties
        
        private long _iD;

        /// <summary>
        /// Gets or sets the ID column value.
        /// </summary>
        [Column(Name="ID", Storage="_iD", DbType="bigint NOT NULL", IsPrimaryKey=true, CanBeNull=false)]
        public long ID
        {
            get { return _iD; }
            set
            {
                if (_iD != value)
                {
                    OnIDChanging(value);
                    OnPropertyChanging("ID");
                    _iD = value;
                    OnPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        
        private string _title;

        /// <summary>
        /// Gets or sets the Title column value.
        /// </summary>
        [Column(Name="Title", Storage="_title", DbType="nvarchar(50) NOT NULL", CanBeNull=false)]
        public string Title
        {
            get { return _title; }
            set
            {
                if (_title != value)
                {
                    OnTitleChanging(value);
                    OnPropertyChanging("Title");
                    _title = value;
                    OnPropertyChanged("Title");
                    OnTitleChanged();
                }
            }
        }
        
        private long _siteID;

        /// <summary>
        /// Gets or sets the SiteID column value.
        /// </summary>
        [Column(Name="SiteID", Storage="_siteID", DbType="bigint NOT NULL", CanBeNull=false)]
        public long SiteID
        {
            get { return _siteID; }
            set
            {
                if (_siteID != value)
                {
                    if (_siteSiteInfo.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnSiteIDChanging(value);
                    OnPropertyChanging("SiteID");
                    _siteID = value;
                    OnPropertyChanged("SiteID");
                    OnSiteIDChanged();
                }
            }
        }
        #endregion
        
        #region Association Mapped Properties
        
        private EntityRef<SiteInfo> _siteSiteInfo;

        /// <summary>
        /// Gets or sets the SiteInfo association.
        /// </summary>
        [Association(Name="FK_Tag_SiteInfo", Storage="_siteSiteInfo", ThisKey="SiteID", OtherKey="ID", IsForeignKey=true)]
        public SiteInfo SiteSiteInfo
        {
            get { return _siteSiteInfo.Entity; }
            set
            {
                SiteInfo previousValue = _siteSiteInfo.Entity;
                if (previousValue != value || _siteSiteInfo.HasLoadedOrAssignedValue == false)
                {
                    OnPropertyChanging("SiteSiteInfo");
                    if (previousValue != null)
                    {
                        _siteSiteInfo.Entity = null;
                        previousValue.SiteTagList.Remove(this);
                    }
                    _siteSiteInfo.Entity = value;
                    if (value != null)
                    {
                        value.SiteTagList.Add(this);
                        _siteID = value.ID;
                    }
                    else
                    {
                        _siteID = default(long);
                    }
                    OnPropertyChanged("SiteSiteInfo");
                }
            }
        }
        
        private EntitySet<ArticleTag> _articleTagList;
        
        /// <summary>
        /// Gets or sets the ArticleTag association.
        /// </summary>
        [Association(Name="FK_ArticleTag_Tag", Storage="_articleTagList", ThisKey="ID", OtherKey="TagID")]
        public EntitySet<ArticleTag> ArticleTagList
        {
            get { return _articleTagList; }
            set { _articleTagList.Assign(value); }
        }
        
        [DebuggerNonUserCodeAttribute()]
        private void Attach_ArticleTagList(ArticleTag entity)
        {
            OnPropertyChanging(null);
            entity.Tag = this;
            OnPropertyChanged(null);
        }
        
        [DebuggerNonUserCodeAttribute()]
        private void Detach_ArticleTagList(ArticleTag entity)
        {
            OnPropertyChanging(null);
            entity.Tag = null;
            OnPropertyChanged(null);
        }
        
        private EntitySet<UrlTag> _urlTagList;
        
        /// <summary>
        /// Gets or sets the UrlTag association.
        /// </summary>
        [Association(Name="FK_UrlTag_Tag", Storage="_urlTagList", ThisKey="ID", OtherKey="TagID")]
        public EntitySet<UrlTag> UrlTagList
        {
            get { return _urlTagList; }
            set { _urlTagList.Assign(value); }
        }
        
        [DebuggerNonUserCodeAttribute()]
        private void Attach_UrlTagList(UrlTag entity)
        {
            OnPropertyChanging(null);
            entity.Tag = this;
            OnPropertyChanged(null);
        }
        
        [DebuggerNonUserCodeAttribute()]
        private void Detach_UrlTagList(UrlTag entity)
        {
            OnPropertyChanging(null);
            entity.Tag = null;
            OnPropertyChanged(null);
        }
        #endregion
        
        #region Extensibility Method Definitions
        /// <summary>Called when this instance is loaded.</summary>
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        partial void OnValidate(ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        partial void OnCreated();
        /// <summary>Called when ID is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnIDChanging(long value);
        /// <summary>Called after ID has Changed.</summary>
        partial void OnIDChanged();
        /// <summary>Called when Title is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnTitleChanging(string value);
        /// <summary>Called after Title has Changed.</summary>
        partial void OnTitleChanged();
        /// <summary>Called when SiteID is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnSiteIDChanging(long value);
        /// <summary>Called after SiteID has Changed.</summary>
        partial void OnSiteIDChanged();
        #endregion
        
    }
}

