
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Diagnostics;

namespace YouXiArticle.Models
{
    /// <summary>
    /// The class representing the dbo.UrlTag table.
    /// </summary>
    [Table(Name="dbo.UrlTag")]
    public partial class UrlTag
        : YouXiArticleEntity
    {
        
        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="UrlTag"/> class.
        /// </summary>
        [DebuggerNonUserCodeAttribute()]
        public UrlTag()
        {
            OnCreated();
            _tag = default(EntityRef<Tag>);
            _urlAction = default(EntityRef<UrlAction>);
        }
        #endregion
        
        #region Column Mapped Properties
        
        private long _iD = default(long);

        /// <summary>
        /// Gets the ID column value.
        /// </summary>
        [Column(Name="ID", Storage="_iD", DbType="bigint NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true, CanBeNull=false)]
        public long ID
        {
            get { return _iD; }
            set
            {
                if (_iD != value)
                {
                    OnIDChanging(value);
                    OnPropertyChanging("ID");
                    _iD = value;
                    OnPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        
        private long _tagID;

        /// <summary>
        /// Gets or sets the TagID column value.
        /// </summary>
        [Column(Name="TagID", Storage="_tagID", DbType="bigint NOT NULL", CanBeNull=false)]
        public long TagID
        {
            get { return _tagID; }
            set
            {
                if (_tagID != value)
                {
                    if (_tag.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnTagIDChanging(value);
                    OnPropertyChanging("TagID");
                    _tagID = value;
                    OnPropertyChanged("TagID");
                    OnTagIDChanged();
                }
            }
        }
        
        private long _urlActionID;

        /// <summary>
        /// Gets or sets the UrlActionID column value.
        /// </summary>
        [Column(Name="UrlActionID", Storage="_urlActionID", DbType="bigint NOT NULL", CanBeNull=false)]
        public long UrlActionID
        {
            get { return _urlActionID; }
            set
            {
                if (_urlActionID != value)
                {
                    if (_urlAction.HasLoadedOrAssignedValue)
                    {
                        throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
                    }
                    OnUrlActionIDChanging(value);
                    OnPropertyChanging("UrlActionID");
                    _urlActionID = value;
                    OnPropertyChanged("UrlActionID");
                    OnUrlActionIDChanged();
                }
            }
        }
        #endregion
        
        #region Association Mapped Properties
        
        private EntityRef<Tag> _tag;

        /// <summary>
        /// Gets or sets the Tag association.
        /// </summary>
        [Association(Name="FK_UrlTag_Tag", Storage="_tag", ThisKey="TagID", OtherKey="ID", IsForeignKey=true)]
        public Tag Tag
        {
            get { return _tag.Entity; }
            set
            {
                Tag previousValue = _tag.Entity;
                if (previousValue != value || _tag.HasLoadedOrAssignedValue == false)
                {
                    OnPropertyChanging("Tag");
                    if (previousValue != null)
                    {
                        _tag.Entity = null;
                        previousValue.UrlTagList.Remove(this);
                    }
                    _tag.Entity = value;
                    if (value != null)
                    {
                        value.UrlTagList.Add(this);
                        _tagID = value.ID;
                    }
                    else
                    {
                        _tagID = default(long);
                    }
                    OnPropertyChanged("Tag");
                }
            }
        }
        
        private EntityRef<UrlAction> _urlAction;

        /// <summary>
        /// Gets or sets the UrlAction association.
        /// </summary>
        [Association(Name="FK_UrlTag_UrlAction", Storage="_urlAction", ThisKey="UrlActionID", OtherKey="ID", IsForeignKey=true)]
        public UrlAction UrlAction
        {
            get { return _urlAction.Entity; }
            set
            {
                UrlAction previousValue = _urlAction.Entity;
                if (previousValue != value || _urlAction.HasLoadedOrAssignedValue == false)
                {
                    OnPropertyChanging("UrlAction");
                    if (previousValue != null)
                    {
                        _urlAction.Entity = null;
                        previousValue.UrlTagList.Remove(this);
                    }
                    _urlAction.Entity = value;
                    if (value != null)
                    {
                        value.UrlTagList.Add(this);
                        _urlActionID = value.ID;
                    }
                    else
                    {
                        _urlActionID = default(long);
                    }
                    OnPropertyChanged("UrlAction");
                }
            }
        }
        #endregion
        
        #region Extensibility Method Definitions
        /// <summary>Called when this instance is loaded.</summary>
        partial void OnLoaded();
        /// <summary>Called when this instance is being saved.</summary>
        partial void OnValidate(ChangeAction action);
        /// <summary>Called when this instance is created.</summary>
        partial void OnCreated();
        /// <summary>Called when ID is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnIDChanging(long value);
        /// <summary>Called after ID has Changed.</summary>
        partial void OnIDChanged();
        /// <summary>Called when TagID is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnTagIDChanging(long value);
        /// <summary>Called after TagID has Changed.</summary>
        partial void OnTagIDChanged();
        /// <summary>Called when UrlActionID is changing.</summary>
        /// <param name="value">The new value.</param>
        partial void OnUrlActionIDChanging(long value);
        /// <summary>Called after UrlActionID has Changed.</summary>
        partial void OnUrlActionIDChanged();
        #endregion
        
    }
}

